export {Persona} from './componentes/persona';
export {Usuarios} from './componentes/usuarios';
export {Roles} from './componentes/roles';
export {Unidad} from './componentes/unidad';
export {UsuarioSolicitante} from './componentes/usuario_solicitante';
export {Correo} from './componentes/correo';
export {DetalleCorreo} from './componentes/detalleCorreo';
export {Reclamos} from './componentes/reclamos';
export {Plataforma} from './componentes/Plataforma';